### PR TITLE
WEBAPP-585: Add "appname" to translation function

### PR DESCRIPTION
**Pull request by Taggotty**
This pull request belongs to an issue on our [bugtracker](https://issues.integreat-app.de/). 
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword **WEBAPP**.

### CODE REVIEW

**Comment by Taggotty** [comment]
Should be merged together with NATIVE-552, right?

**Comment by klinzo** [comment]
@Taggotty as far as I understand, you can merge this separately as this does not change anything before the new malte locales (and the `{{appName}}` variables) are used. I asked the same thing in https://github.com/Integreat/integreat-react-native-app/pull/288. @maxammann or am I wrong here?

**Comment by Taggotty** [comment]
> Did you check all relevant keys as mentioned here? [Integreat/integreat-react-native-app#288 (comment)](https://github.com/Integreat/integreat-react-native-app/pull/288#issuecomment-669267465)
> 
> I just noticed that you have pulled from [Integreat/integreat-locales#14](https://github.com/Integreat/integreat-locales/pull/14), right? If so, you have to either wait until that PR is merged or revert pulling the locales from that branch. I'd prefer the latter as waiting for the malte locales can take some time. But before doing anything, best check back with @maxammann

Alright. I will ask @maxammann directly what should be prefered. I am fine with both actually :)

**Comment by klinzo** [comment]
So we got the translated locales this weekend, so I guess we could merge them next week.

**Comment by maxammann** [comment]
In dem task musst du nicht von dem locales repo pullen. Also am besten die commits da wieder rauswerfen

dann ist der PR auch nicht so groß.

ca wie der hier: https://github.com/Integreat/integreat-react-native-app/pull/288

**Review by klinzo — APPROVED** [review]

**Review by maxammann — APPROVED** [review]

**Pull request merged**
