### PR TITLE
WEBAPP-88, WEBAPP-171: Change linter warnings to errors, fix all linting errors

### PR DESCRIPTION
**Pull request by klinzo**

### CODE REVIEW

**Comment by klinzo** [comment]
I think I have to check my commit messages more carefully...

**Comment by Schedulaar** [comment]
Maybe you can check if and how we could make css linter less annoying while developing (like allowing wrong order of css properties in dev mode)

**Comment by Schedulaar** [comment]
You can do that by editing webpack.config.js: 
Repalce
```javascript
new StyleLintPlugin({
      files: '**/*.css',
      configFile: 'stylelint.config.js'
    }),
```
with
```javascript
new StyleLintPlugin({
      files: '**/*.css',
      configFile: 'stylelint.config.js',
      emitErrors: !isDebug
    }),
```

**Comment by klinzo** [comment]
@Schedulaar good suggestion, done

**Pull request merged**
